extend type Query{
    chat (chatId: String!): Chat!
    everyChat: [Chat!]
}


type Chat{
    chatId: String!
    creationDate: Long!
    members: [UserProfile!]!
    messages: PagedMessages!
    archived: [String!]
}


type PagedChats{
    content: [Chat!]
    pageSize: Int
    pageNumber: Int
    totalRecords: Long
    totalPages: Int
}

type PagedGroups{
    content: [GroupChat!]
    pageSize: Int
    pageNumber: Int
    totalRecords: Long
    totalPages: Int
}


type GroupChat{
    chatId: String!
    name: String!
    creationDate: Long!
    members : [UserProfile!]!
    memberEntry: [JoinDateEntry!]!
    admins: [UserProfile!]!
    messages: PagedMessages!
    archived: [String!]
}


type JoinDateEntry{
    userId: String!
    timestamp: Long!
}


