extend type Query{
    Message(messageId: String!): Message!
    searchMessage(messageBody: String!): [Message!]
    everyMessage: [Message!]
}

type PagedMessages{
    content: [MessageResponse!]
    pageSize: Int
    pageNumber: Int
    totalRecords: Long
    totalPages: Int
}

type Message{
    messageId: String!
    timestamp: Long!
    content: String!
    username: String!
    userId: String!
    associatedChat: String!
    deletedForUser: [String]!
}

type MessageResponse{
    username: String!
    userId: String!
    chatId: String!
    content: String!
    timestamp: Long!
}

