version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: 'wrongtzapp'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
 doc