services:
  db:
    image: mysql
    restart: always
    container_name: 'wrongtzapp'
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'