services:
  db:
    image: mysql
    restart: always
    container_name: 'wrongtzapp'
    environment:
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - database:/var/lib/docker/volumes/database/_data
volumes:
  database:
    external: true
